### ISSUE TITLE
bug in Clutter Free

### ISSUE THREAD

**Issue by nickdesaulniers** [adityabhaskar/DoneForChrome#2]
Hey Aditya, thanks for making Clutter Free.  I find it useful.  Sorry for providing feedback in such an odd way, but there's a bug I recently found:

chrome tab kept stealing focus.

When clicking into a different tab, focus would return to a different tab.  When I minimized the window, the window reappeared.

Stops if I disable the addon Clutter Free.

Looks like it can't handle these URL's where one redirects to another.
https://en.wikipedia.org/wiki/Dynamic_linker
https://en.wikipedia.org/wiki/Dynamic_library

**Comment by adityabhaskar** [comment]
Hi Nick

Thanks for the feedback!

I'm aware about the issue with automatic redirects. I've got a blunt solution for it in place for most troublesome URLs (shortened URLs). 

For other redirecting URLs, like the ones you shared, I'm planning to implement an interim solution that'll stop the redirects after 2 switches. Still hunting for a proper solution, though.

Will post here when the interim solution is published.

Cheers!

Adi
